/**
 * The tray icons are the palette's seventh restatement, and it had already rotted.
 *
 * `electron/tray.ts` carries three PNGs as base64 because the tray needs an
 * icon that works identically in dev and in the packaged app. They are
 * generated by `scripts/make_tray_icons.py`, by hand, and pasted in — so
 * nothing connected them to the palette they are supposed to match.
 *
 * They were `#4ade80 / #fbbf24 / #f87171`, the Tailwind 400s from *before* the
 * palette moved to measured values. Days out of date, on the one surface with
 * no test and no screenshot covering it, which is exactly why nobody noticed.
 *
 * This decodes the pixels back out and compares them to the tokens. The script
 * now reads `tokens.js` rather than restating it, so the two can only disagree
 * if somebody forgets to re-run it — which is precisely the failure to catch.
 *
 * Lives under `src/` because that is what vitest collects, and reads
 * `electron/tray.ts` as text — the same shape `acrylic.test.ts` already uses
 * to assert on `electron/main.ts`.
 */

import { inflateSync } from 'node:zlib'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { COLORS, hexToRgb } from '@/styles/tokens'

const TRAY = readFileSync(join(process.cwd(), 'electron/tray.ts'), 'utf8')

/** The `name: '<base64>'` entries from `ICON_PNG`. */
function icons(): Record<string, string> {
  const found: Record<string, string> = {}
  for (const [, name, data] of TRAY.matchAll(/^ {2}(ok|warn|bad): '([A-Za-z0-9+/=]+)',$/gm)) {
    found[name] = data
  }
  return found
}

/**
 * The colour at the centre of a 32×32 RGBA PNG.
 *
 * Hand-rolled rather than pulling in a decoder: these are written by a
 * stdlib-only Python script with one IDAT chunk and filter type 0 on every
 * row, so the whole job is inflate, then skip the per-row filter byte. A
 * dependency to read four bytes would be a worse trade than twenty lines.
 */
function centrePixel(base64: string): [number, number, number] {
  const png = Buffer.from(base64, 'base64')

  let idat = Buffer.alloc(0)
  let offset = 8 // the PNG signature
  while (offset < png.length) {
    const length = png.readUInt32BE(offset)
    const type = png.toString('ascii', offset + 4, offset + 8)
    if (type === 'IDAT') idat = Buffer.concat([idat, png.subarray(offset + 8, offset + 8 + length)])
    offset += length + 12 // length + type + data + crc
  }

  const raw = inflateSync(idat)
  const size = 32
  const stride = size * 4 + 1 // one filter byte per row
  const row = Math.floor(size / 2)
  const start = row * stride + 1 + Math.floor(size / 2) * 4
  return [raw[start], raw[start + 1], raw[start + 2]]
}

describe('the tray icons', () => {
  it('has one for each state it claims to', () => {
    expect(Object.keys(icons()).sort()).toEqual(['bad', 'ok', 'warn'])
  })

  it.each(['ok', 'warn', 'bad'] as const)('draws %s in the palette colour', (name) => {
    // The whole point: a hand-pasted asset that silently disagrees with the
    // tokens is invisible until somebody looks at their taskbar and squints.
    expect(centrePixel(icons()[name])).toEqual(hexToRgb(COLORS[name]))
  })

  it('does not still carry the pre-retheme Tailwind 400s', () => {
    // Named explicitly, because "it matches the tokens" would also pass if
    // somebody changed the tokens back rather than regenerating the icons.
    const stale = ['#4ade80', '#fbbf24', '#f87171']
    for (const name of ['ok', 'warn', 'bad'] as const) {
      const [r, g, b] = centrePixel(icons()[name])
      const hex = `#${[r, g, b].map((c) => c.toString(16).padStart(2, '0')).join('')}`
      expect(stale).not.toContain(hex)
    }
  })
})
